version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_api_empresas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: api_empresas
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apiuser123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_network

  api:
    build: .
    container_name: api_empresas
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=api_empresas;User=apiuser;Password=apiuser123;"
    networks:
      - api_network

networks:
  api_network:

volumes:
  mysql_data:
